// ============================================================
// Build — Badminton Sports Day 2026
// Bundles + minifies the classic-script app into dist/ WITHOUT
// changing the architecture: JS is concatenated in load order
// (one global scope, exactly like the original single file) and
// minified WITHOUT renaming identifiers, so every inline onclick
// and cross-file global keeps working. CSS is concatenated + minified.
// ============================================================
import { transform } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = dirname(fileURLToPath(import.meta.url));
const DIST = join(root, 'dist');
const ASSETS = join(DIST, 'assets');

// ---- load order (must match index.html / umpire.html) ----
const CSS = ['base','login','nav','scoreboard','match-cards','tables-modals','dashboard','picker','board',
  'notifications','ongoing-finished','climax','fullscreen','report','gallery','trophy',
  'responsive','profile','components','backup','qr','tv'].map(n => `css/${n}.css`);

const JS = [
  'shared/firebase-config.js',
  'js/utils.js','js/auth.js','js/core.js','js/ui.js',
  'js/player-photo.js','js/player-profile.js','js/me.js','js/gallery.js','js/career.js','js/season.js','js/export-import.js',
  'js/match-picker.js','js/match-render.js','js/result-entry.js','js/stats.js',
  'js/reports.js','js/pdf-export.js','js/dashboard.js','js/ranking.js',
  'js/effects.js','js/notifications.js','js/backup.js',
  'js/vendor/qrcode.min.js','js/qr.js','js/tv.js',
  'shared/pwa.js',
];

const UMP_CSS = ['css/umpire.css'];
const UMP_JS  = ['shared/firebase-config.js','shared/pwa.js','umpire/umpire.js'];

const ICONS = readdirSync(join(root,'icons')).filter(f => f.endsWith('.png'));
const COPY = ['manifest.webmanifest','umpire.webmanifest', ...ICONS.map(f => `icons/${f}`)];

const read = (p) => readFileSync(join(root, p), 'utf8');
// join with ";\n" so a file that omits a trailing semicolon can't merge tokens with the next
const concat = (files) => files.map(read).join('\n;\n');

async function minifyJs(code) {
  const r = await transform(code, {
    loader: 'js',
    minifyWhitespace: true,
    minifySyntax: true,
    minifyIdentifiers: false, // keep global names → inline onclick + cross-file globals stay valid
    legalComments: 'none',
  });
  return r.code;
}
async function minifyCss(code) {
  const r = await transform(code, { loader: 'css', minify: true, legalComments: 'none' });
  return r.code;
}

// strip <link css/*> and app <script> lines, inject single bundle refs
function rewriteHtml(srcFile, { cssHref, jsHref, jsPattern }) {
  const lines = read(srcFile).split('\n');
  const out = [];
  let cssDone = false, jsDone = false;
  const isCss = (t) => /^<link rel="stylesheet" href="css\/[^"]+\.css">$/.test(t);
  const isJs  = (t) => jsPattern.test(t);
  for (const line of lines) {
    const t = line.trim();
    if (isCss(t)) { if (!cssDone) { out.push(`<link rel="stylesheet" href="${cssHref}">`); cssDone = true; } continue; }
    if (isJs(t))  { if (!jsDone)  { out.push(`<script defer src="${jsHref}"></script>`); jsDone = true; } continue; }
    out.push(line);
  }
  return out.join('\n');
}

function makeSw() {
  const shell = ['./','index.html','umpire.html','manifest.webmanifest','umpire.webmanifest',
    'assets/app.css','assets/app.js','assets/umpire.css','assets/umpire.js',
    ...ICONS.map(f => `icons/${f}`)];
  const list = shell.map(u => `  ${JSON.stringify(u)}`).join(',\n');
  return `// Auto-generated by build.mjs — do not edit. Precaches the built shell.
const CACHE = 'bdm2026-shell-v10';
const SHELL = [
${list}
];
self.addEventListener('install', (e) => { e.waitUntil(caches.open(CACHE).then((c) => Promise.allSettled(SHELL.map((u) => c.add(u)))).then(() => self.skipWaiting())); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const req = e.request; if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // HTML network-first: a cached document next to freshly revalidated JS
  // can run code its own script tags never loaded.
  if (req.mode === 'navigate' || (req.headers.get('accept') || '').includes('text/html')) {
    e.respondWith(fetch(req).then((res) => { if (res && res.status === 200) caches.open(CACHE).then((c) => c.put(req, res.clone())); return res; }).catch(() => caches.open(CACHE).then((c) => c.match(req).then((hit) => hit || c.match('index.html')))));
    return;
  }
  if (url.origin !== location.origin) {
    if (url.hostname === 'www.gstatic.com') {
      e.respondWith(caches.open(CACHE).then((c) => c.match(req).then((hit) => hit || fetch(req).then((res) => { c.put(req, res.clone()); return res; }))));
    }
    return;
  }
  e.respondWith(caches.open(CACHE).then((c) => c.match(req).then((hit) => {
    const net = fetch(req).then((res) => { if (res && res.status === 200 && res.type === 'basic') c.put(req, res.clone()); return res; }).catch(() => hit);
    return hit || net;
  })));
});
`;
}

async function build() {
  rmSync(DIST, { recursive: true, force: true });
  mkdirSync(ASSETS, { recursive: true });
  mkdirSync(join(DIST, 'icons'), { recursive: true });

  // bundles
  writeFileSync(join(ASSETS, 'app.css'),    await minifyCss(concat(CSS)));
  writeFileSync(join(ASSETS, 'app.js'),     await minifyJs(concat(JS)));
  writeFileSync(join(ASSETS, 'umpire.css'), await minifyCss(concat(UMP_CSS)));
  writeFileSync(join(ASSETS, 'umpire.js'),  await minifyJs(concat(UMP_JS)));

  // html
  writeFileSync(join(DIST, 'index.html'), rewriteHtml('index.html', {
    cssHref: 'assets/app.css', jsHref: 'assets/app.js',
    jsPattern: /^<script defer src="(shared\/firebase-config\.js|shared\/pwa\.js|js\/[^"]+\.js)"><\/script>$/,
  }));
  writeFileSync(join(DIST, 'umpire.html'), rewriteHtml('umpire.html', {
    cssHref: 'assets/umpire.css', jsHref: 'assets/umpire.js',
    jsPattern: /^<script defer src="(shared\/firebase-config\.js|shared\/pwa\.js|umpire\/umpire\.js)"><\/script>$/,
  }));

  // static copies + generated sw
  for (const f of COPY) { mkdirSync(dirname(join(DIST, f)), { recursive: true }); copyFileSync(join(root, f), join(DIST, f)); }
  writeFileSync(join(DIST, 'sw.js'), makeSw());

  // report sizes
  const kb = (p) => (readFileSync(join(DIST, p)).length / 1024).toFixed(1) + 'kb';
  const srcJs = concat(JS).length, srcCss = concat(CSS).length;
  console.log('✓ dist/assets/app.js   ', kb('assets/app.js'),  '(from ' + (srcJs/1024).toFixed(1) + 'kb source)');
  console.log('✓ dist/assets/app.css  ', kb('assets/app.css'), '(from ' + (srcCss/1024).toFixed(1) + 'kb source)');
  console.log('✓ dist/assets/umpire.js', kb('assets/umpire.js'));
  console.log('✓ dist/assets/umpire.css', kb('assets/umpire.css'));
  console.log('✓ dist/index.html, umpire.html, sw.js, manifests, icons/');
}
build().catch((e) => { console.error('BUILD FAILED:', e.message); process.exit(1); });
